# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https:/jlchristian.com/jlchristian.comdocs.github.com/jlchristian.comgithub/jlchristian.comadministering-a-repository/jlchristian.comconfiguration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "ruby" # See documentation for possible values
    directory: "/jlchristian.com" # Location of package manifests
    schedule:
      interval: "'daily"
