site: J.L. Christian
title: J.L. Christian
greetings: Codex Portfolio 
description: >- 
  A portfolio of my creative works and collabrations 
  **Site Description**  

Welcome to the online portfolio of J.L. Christian. This is porfolio of curated collection of my finest works, exploring the intersections of fine art, digital design, and collaborative storytelling.  

**Overview**  

On this site, you will find a comprehensive portfolio detailing my artistic journey and professional expertise. Expect to discover  

- **Processes** An inside look into my creative process, from conceptualization to completion, highlighting the meticulous techniques and inspirations behind each project.  
- **Digital Art** A diverse array of visually striking digital artworks that blend traditional artistic principles with cutting-edge technology.  
- **Art Direction** Case studies and projects where I have directed creative visions to life, ensuring cohesive and impactful results.  
- **Collaborations**: A showcase of partnerships with other artists, brands, and creative professionals, emphasizing the power of collaboration in creating unique works.  

Whether you're here to admire, collaborate, or commission, my portfolio site offers a seamless and inspiring journey through my artistic endeavors.

site: Portfolio

title: J.L. Christian Port
greetings: Hello there! 👋

title: J.L. Christian Portfolio
greetings: Codex Portfolio

description: >-
  A portfolio of my creative works and collabrations

lang: en-US
timezone:  US/California 

repo:  # site repo [optional]


data-theme: light # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: Seimi Nomore
  bio: Fine Artist | Art Director
  userpicture: 
  username: # general username
  github: Seiminomore # github username
  twitter: # twitter username
  mastodon: hachyderm.io/@davidebri # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: your-email@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings

url: "https://seiminomore.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/port02" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.


permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  

relative_links:
  enabled:     true
  collections: false


