site: J.L. Christian - Portfolio
title: J.L. Christian - Portfolio
description: >
  Welcome to the online portfolio of J.L. Christian. This portfolio includes:
  - Processes: Insight into the creative process, from conceptualization to completion.
  - Digital Art: A diverse array of visually striking digital artworks.
  - Art Direction: Case studies and projects showcasing cohesive results.
  - Collaborations: Highlights of partnerships and unique works.

lang: en-US
timezone: US/California
data-theme: light

author:
  name: J.L. Christian
  bio: >
    This portfolio serves as an index of my creative works, projects, and collaborations.
  userpicture: /assets/img/JLC-Recovered.png
  github: SeimiNomore

url: "https://seiminomore.github.io"
baseurl: ""

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  

relative_links:
  enabled:     true
  collections: false


